### ISSUE TITLE
return array vann strings?

### ISSUE THREAD

**Issue by eriklenaerts** [digipolisantwerpdocumentation/api-requirements#25]
Hey, volgens de spec moeten arrays ge-encapsuleert worden in een object omdat sommige frameworks er moeilijkheden met zouden hebben. Nu is m'n vraag of een simpele array van strings ook moet ge-encapsuleerd worden? Draagt niet veel bij aan de leesbaarheid, lijkt me wat overkill...
example:
{
  [
    "DELIVERABLE",
    "ADDON",
    "POLICY"
  ]
}

swagger validator is nogal streng imho ;)

**Comment by Eriklommelen** [comment]
Erik,


In de DA requirements staat dat array's steeds ge-encapsuleert worden.



*Met vriendelijke groeten *

Erik Lommelen
Digipolis WSO2 ESB\WSO2 IS\ACPaaS-Team
Generaal Armstrongweg 1
2020 Antwerpen
Gsm: +32 499 54 99 80, Fax: +32 3 338 79 00

www.digipolis.be/

P Denk aan het milieu vooraleer je mails print - Disclaimer

**Comment by PeterClaes** [comment]
@eriklenaerts : json bestaat vooral uit key / value  objecten en om overal consequent te zijn, wordt dit dus over de hele lijn doorgetrokken.
