### ISSUE TITLE
Api requirements Search

### ISSUE THREAD

**Issue by stefanpante** [digipolisantwerpdocumentation/api-requirements#9]
Om te zoeken wordt er in de challenge van atypisch search  een POST /search gedaan in plaats van een GET /search. 

Dit omdat er met zoekacties nogal snel op de limieten van de lengte van query parameters gebotst wordt.

Nu komt het volgende issue hierbij ook boven:
waar horen de **page** & **pagesize** dan thuis?

Na discussie hierover hebben we twee insteken:

1. Deze parameters ook mee in de body van de post. Omdat de rest van de query hier ook geplaatst wordt.

2. Deze parameters toch als queryparams in de url. Anders zijn de links in de hal+json wrapper nogal  nutteloos.

We zouden dit graag uitgeklaard zien, 
zodat we in de toekomst geen vertraging oplopen als we de API live willen zetten.

Met vriendelijke groeten,
Stefan

**Comment by PeterClaes** [comment]
uit de requirements : 

POST | voor het uitvoeren van een controller(=command) (werkwoord, vb. search) | representatie van info voor controller | optioneel
-- | -- | -- | --

### Paginatie ###
altijd gebruiken bij ophalen van collecties
query parameters : **page**= en **pagesize**=


Dus volgens de requirements ga ik voor jullie 2e optie : page en pagesize in querystring.
